name: CICD
trigger:
  - main
variables:
  - name: PROJECT_ENVIRONMENT
    value: $(PROJECT_ENVIRONMENT)
  - name: CLUSTER_NAME
    value: $(CLUSTER_NAME)
  - name: DATABRICKS_HOST
    value: $(DATABRICKS_HOST)
  - name: DATABRICKS_TOKEN
    value: $DATABRICKS_TOKEN)
steps:
  - task: usePythonVersion@0 
    displayName: 'Use Python 3.9'
    inputs:
      versionSpec: 3.9
  - script: make install-dependencies
  - script: make connect-with-databricks
  - script: make update-file-dependencies