name: CICD
trigger:
  - main
variables:
  - name: PROJECT_ENVIRONMENT
    value: $(PROJECT_ENVIRONMENT)
  - name: CLUSTER_NAME
    value: $(CLUSTER_NAME)
  - name: DATABRICKS_HOST
    value: $(DATABRICKS_HOST)
  - name: DATABRICKS_TOKEN
    value: $DATABRICKS_TOKEN)
stages:
  - stage: UpdateCondaDependencies
    jobs:
      - job: InstallDependencies
        steps:
          - displayName: 'Use Python 3.9'
            task: usePythonVersion@0
            inputs:
              versionSpec: 3.9
          - displayName: 'Install Dependencies'
            script: make install-dependencies
          - displayName: 'Connect with Databricks'
            script: make connect-with-databricks
          - displayName: 'Update file dependencies'
            script: make update-file-dependencies