name: __NAME__

channels:
  - default
  - conda-forge
dependencies:
  - python=3.9
  - pyspark
  - pytest
  - mlflow
  - pandas
  - numpy
  - scikit-learn
  - mysql-connector-python
  - mysqlclient
  - azure-storage-blob
