name: CICD
on:
  push:
    branches: [ main ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      PROJECT_ENVIRONMENT: ${{ secrets.PROJECT_ENVIRONMENT }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Databricks-CLI
        run: make install-dependencies
      - name: Set Databricks credentials
        run: |
        sh ./scripts/databricks/create-cfg.sh
      - name: Configure databricks
        run: databricks configure
      # - name: Connec with azure databricks service
      #   run: make connect-with-databricks
      # - name: Copy dependencies from the databricks cluster to conda.yml
      #   run: make update-file-dependencies

