name: CICD
on:
  push:
    branches: [ main ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      PROJECT_ENVIRONMENT: ${{ secrets.PROJECT_ENVIRONMENT }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      DATABRICKS_HOST: https://adb-4536027512959997.17.azuredatabricks.net
      DATABRICKS_TOKEN: dapif0d29da903ef60c132cfbcb1f7c077ad-2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Databricks-CLI
        run: make install-dependencies
      - name: Set Databricks credentials
        env:
        run: |
          cat > ~/.databrickscfg  <<EOF
          [DEFAULT] 
          host = "$DATABRICKS_HOST"
          token = "$DATABRICKS_TOKEN" 
          EOF
      - name: Print environment variables
        run: printenv
      - name: Cat databricks configuration
        run: cat ~/.databrickscfg
      - name: Configure databricks
        run: databricks configure
      # - name: Connec with azure databricks service
      #   run: make connect-with-databricks
      # - name: Copy dependencies from the databricks cluster to conda.yml
      #   run: make update-file-dependencies

