name: CICD
on:
  push:
    branches: [ main ]
    paths:
      - src/**
jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      PROJECT_ENVIRONMENT: ${{ secrets.PROJECT_ENVIRONMENT }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Databricks-CLI
        run: make install-dependencies
      - name: Connec with azure databricks service
        run: make connect-with-databricks
      - name: Update dependencies
        run: make update-file-dependencies
      - name: Create virtual environment
        run: make create-env
      - name: unit testing
        run: make unit-test

